### ISSUE TITLE
Incorrectly identified "google docstring" format should not break building

### ISSUE THREAD

**Issue by Peter200lx** [timothycrosley/pdocs#18]
We had a file with a docstring of something like the following format:
`cat mod/test.py`
```python
def test(param: str) -> str:
    """This is a test

    Args:
        param - poorly formatted
    """
    return param
```
This was not intentionally a google docstring format, it just happens to be of similar structure, while also being incorrectly formatted to be a google docstring (using a `-` instead of a `:`)

With `pdocs==1.0.0` this built fine and included the docstring, but didn't call out the parameters in the generated html (which is fine for our use case).
```
$ pip freeze |grep pdocs
pdocs==1.0.0
$ portray as_html -m mod
/tmp/venv/lib/python3.6/site-packages/portray/config.py:120: UserWarning: 
No config file found at location: "/tmp/pyproject.toml"
  warnings.warn(f'\nNo config file found at location: "{location}"')
/tmp/venv/lib/python3.6/site-packages/portray/config.py:199: UserWarning: Unable to identify `repo_name`, `repo_url`, and `edit_uri` automatically.
  warnings.warn("Unable to identify `repo_name`, `repo_url`, and `edit_uri` automatically.")
Done Copying source documentation to temporary compilation directory
Done Auto generating reference documentation using pdocs
Done Rendering complete website from Markdown using MkDocs

                      __
                     /\ \__
 _____     ___   _ __\ \ ,_\  _ __    __     __  __
/\ '__`\  / __`\/\`'__\ \ \/ /\`'__\/'__`\  /\ \/\ \
\ \ \L\ \/\ \L\ \ \ \/ \ \ \_\ \ \//\ \L\.\_\ \ \_\ \
 \ \ ,__/\ \____/\ \_\  \ \__\\ \_\\ \__/.\_\\/`____ \
  \ \ \/  \/___/  \/_/   \/__/ \/_/ \/__/\/_/ `/___/> \
   \ \_\                                         /\___/
    \/_/                                         \/__/
        Your Project with Great Documentation.

Version: 1.5.0
Copyright Timothy Edmund Crosley 2019 MIT License

Documentation successfully generated into `/tmp/site` !
```

However using `pdocs==1.1.0` the docstring is identified as a google docstring, which then broke our CI building of documents:
```
$ portray as_html -m mod
/tmp/venv/lib/python3.6/site-packages/portray/config.py:120: UserWarning: 
No config file found at location: "/tmp/pyproject.toml"
  warnings.warn(f'\nNo config file found at location: "{location}"')
/tmp/venv/lib/python3.6/site-packages/portray/config.py:199: UserWarning: Unable to identify `repo_name`, `repo_url`, and `edit_uri` automatically.
  warnings.warn("Unable to identify `repo_name`, `repo_url`, and `edit_uri` automatically.")
Done Copying source documentation to temporary compilation directory
Traceback (most recent call last):
  File "/tmp/venv/bin/portray", line 8, in <module>
    sys.exit(__hug__.cli())
  File "/tmp/venv/lib/python3.6/site-packages/hug/api.py", line 441, in __call__
    result = self.commands.get(command)()
  File "/tmp/venv/lib/python3.6/site-packages/hug/interface.py", line 650, in __call__
    raise exception
  File "/tmp/venv/lib/python3.6/site-packages/hug/interface.py", line 646, in __call__
    result = self.output(self.interface(**pass_to_function), context)
  File "/tmp/venv/lib/python3.6/site-packages/hug/interface.py", line 129, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/tmp/venv/lib/python3.6/site-packages/portray/api.py", line 39, in as_html
    overwrite=overwrite,
  File "/tmp/venv/lib/python3.6/site-packages/portray/render.py", line 50, in documentation
    with documentation_in_temp_folder(config) as (_, documentation_output):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/tmp/venv/lib/python3.6/site-packages/portray/render.py", line 149, in documentation_in_temp_folder
    pdocs(config["pdocs"])
  File "/tmp/venv/lib/python3.6/site-packages/portray/render.py", line 60, in pdocs
    pdocs_as_markdown(**config)
  File "/tmp/venv/lib/python3.6/site-packages/pdocs/api.py", line 81, in as_markdown
    roots = _get_root_modules(modules)
  File "/tmp/venv/lib/python3.6/site-packages/pdocs/api.py", line 141, in _get_root_modules
    return [pdocs.extract.extract_module(module_name) for module_name in module_names]
  File "/tmp/venv/lib/python3.6/site-packages/pdocs/api.py", line 141, in <listcomp>
    return [pdocs.extract.extract_module(module_name) for module_name in module_names]
  File "/tmp/venv/lib/python3.6/site-packages/pdocs/extract.py", line 168, in extract_module
    return _extract_module(dname, mname)
  File "/tmp/venv/lib/python3.6/site-packages/pdocs/extract.py", line 149, in _extract_module
    mod.submodules.append(_extract_module(dname, submodule_full_name, parent=mod))
  File "/tmp/venv/lib/python3.6/site-packages/pdocs/extract.py", line 143, in _extract_module
    mod = pdocs.doc.Module(mname, m, parent)
  File "/tmp/venv/lib/python3.6/site-packages/pdocs/doc.py", line 244, in __init__
    self.doc[name] = Function(name, self, obj)
  File "/tmp/venv/lib/python3.6/site-packages/pdocs/doc.py", line 655, in __init__
    super().__init__(name, module, inspect.getdoc(func_obj))
  File "/tmp/venv/lib/python3.6/site-packages/pdocs/doc.py", line 154, in __init__
    self.parsed_docstring = docstring_parser.parse(self.docstring)
  File "/tmp/venv/lib/python3.6/site-packages/docstring_parser/parser.py", line 20, in parse
    rets.append(parse_(text))
  File "/tmp/venv/lib/python3.6/site-packages/docstring_parser/google.py", line 274, in parse
    return GoogleParser().parse(text)
  File "/tmp/venv/lib/python3.6/site-packages/docstring_parser/google.py", line 264, in parse
    ret.meta.append(self._build_meta(part, title))
  File "/tmp/venv/lib/python3.6/site-packages/docstring_parser/google.py", line 106, in _build_meta
    before, desc = text.split(":", 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

For now I've worked around the issue in our local code by changing the `-` to a `:`, but I don't know if there are other instances in other projects. At a high level I do not believe that incorrectly identifying a docstring to be of a specific format should allow the entire process to fail. Instead, it should try to parse as these specific formats, and if it fails, then it should fall back to the old behavior of printing the docstring, but not trying to add the additional parameter table.

**Comment by Peter200lx** [comment]
I can confirm that https://github.com/timothycrosley/pdocs/pull/19 fixed this issue, and the fix is released in version 1.1.1.
